### ISSUE TITLE
Can't compile in xcode 4.6.3

### ISSUE THREAD

**Issue by juanredondo** [infobip/push-plugin-cordova-phonegap#7]
The error on cordova build ios is (and others):
Plugins/com.infobip.push.cordova/IBPush.m:142:9: error: unknown type name 'UIUserNotificationType'; did you mean 'UIRemoteNotificationType'?
        UIUserNotificationType types = UIUserNotificationTypeAlert | UIUserNotificationTypeBadge | UIUserNotificationTypeSound;

Im trying to unistall plugin and platform several times, including with plugman, with no luck.

**Comment by juanredondo** [comment]
Other errors:

Volumes/Almacen/Users/juan/Sources/mo_nomastickets_phonegapapp_android/platforms/ios/NO MAS TICKETS/Plugins/com.infobip.push.cordova/IBPush.m:143:9: error: use of undeclared identifier 'UIUserNotificationSettings'
        UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:types categories:nil];
        ^
/Volumes/Almacen/Users/juan/Sources/mo_nomastickets_phonegapapp_android/platforms/ios/NO MAS TICKETS/Plugins/com.infobip.push.cordova/IBPush.m:143:37: error: use of undeclared identifier 'settings'
        UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:types categories:nil];
                                    ^
/Volumes/Almacen/Users/juan/Sources/mo_nomastickets_phonegapapp_android/platforms/ios/NO MAS TICKETS/Plugins/com.infobip.push.cordova/IBPush.m:143:49: error: use of undeclared identifier 'UIUserNotificationSettings'
        UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:types categories:nil];
                                                ^
/Volumes/Almacen/Users/juan/Sources/mo_nomastickets_phonegapapp_android/platforms/ios/NO MAS TICKETS/Plugins/com.infobip.push.cordova/IBPush.m:144:77: error: use of undeclared identifier 'settings'
        [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
                                                                            ^
/Volumes/Almacen/Users/juan/Sources/mo_nomastickets_phonegapapp_android/platforms/ios/NO MAS TICKETS/Plugins/com.infobip.push.cordova/IBPush.m:145:10: error: no visible @interface for 'UIApplication' declares the selector 'registerForRemoteNotifications'
        [[UIApplication sharedApplication] registerForRemoteNotifications];

**Comment by mmiroslav** [comment]
Hi,
This errors appears because you are using Xcode 4. 
`UIUserNotificationSettings` are supported in Xcode 6 and later. Please upgrade your Xcode to new version.

**Comment by juanredondo** [comment]
Can't install xcode 6, in my old 2006 iMac. 4.6.3 is the last avalible version. Thank's for the hint anyway.
